//
//  Section.swift
//  CodeExam
//
//  Created by riza milani on 11/16/1398 AP.
//  Copyright © 1398 reza milani. All rights reserved.
//

// Source: This file was generated by https://app.quicktype.io/

import Foundation

// MARK: - VPModel
struct VPModel: Codable {
    let title: String
    let vpModelDescription: String
    let links: VPModelLinks

    enum CodingKeys: String, CodingKey {
        case title
        case vpModelDescription = "description"
        case links = "_links"
    }
}


// MARK: - VPModelLinks
struct VPModelLinks: Codable {
    let viaplaySections: [ViaplaySection]

    enum CodingKeys: String, CodingKey {
        case viaplaySections = "viaplay:sections"
    }
}

// MARK: - ViaplaySection
struct ViaplaySection: Codable {
    let id, title, href, type: String
    let name: String
    let templated: Bool
    let active: Bool?
}

